### ISSUE TITLE
Where are the audio files?

### ISSUE THREAD

**Issue by JairusSW** [CircuitMess/Spencer-Firmware#22]
Hey, I'm looking into a playing a youtube stream (music) and I see in src > Funpack > Chickensound.hpp there are a bunch of refs to audio files... Where can I find them?

Also, I'm trying to set up a youtube stream (Via a computer pulling and pushing from local ip)... Would it be possible, or is the board not powerful enough?

**Comment by matjaz** [comment]
files are stored directly on Spencer storage.
